import { Inter } from 'next/font/google'
import Footer from './Components/Footer'
import UserHeader from './Components/UserHeader'
import './globals.css'
import  {store} from './redux/store.js';
import { Provider } from 'react-redux';


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <Provider store={store}>
      <html lang="en">
      <body className={inter.className}>
      <UserHeader/>
        {children}
        <Footer/>
        </body>
        </html>
        </Provider>
  )
}
